spring:
  application:
    name: maldallija-be
  profiles:
    active: local

auth:
  access-session:
    expiry-hours: 1
  refresh-session:
    expiry-days: 30

management:
  endpoints:
    web:
      base-path: /api
      path-mapping:
        health: health-check
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
